Add combined certificate workflow

diff --git a/.github/workflows/renew-cert.yml b/.github/workflows/renew-cert.yml
--- a/.github/workflows/renew-cert.yml
+++ b/.github/workflows/renew-cert.yml
@@ -60,12 +60,13 @@ jobs:
 
       - name: 6. 保存证书到仓库
         run: |
+          # 注意：更新仓库需要预先设置工作流读写权限，打开仓库mycert-Settings-Actions-General-滚到Workflow permissions-读写-Save
           echo "==> pwd" && pwd
           echo "==> ls -la" && ls -la
           echo "==> ls -la ~/" && ls -la ~/
           echo "==> ls -la ~/.acme.sh" && ls -la ~/.acme.sh
-          echo "==> ls $(pwd)/* -R | grep gao && mv gao* certs || echo Not Found"
-          ls $(pwd)/* -R | grep gao && mv gao* certs || echo Not Found
+          echo "==> ls | grep gao && mv gao* certs || echo Not Found"
+          ls | grep gao && mv gao* certs || echo Not Found"
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"
           git add certs/
