Add combined certificate workflow

diff --git a/.github/workflows/renew-cert.yml b/.github/workflows/renew-cert.yml
--- a/.github/workflows/renew-cert.yml
+++ b/.github/workflows/renew-cert.yml
@@ -40,7 +40,7 @@ jobs:
           echo "==> ls -la" && ls -la
           echo "==> ls -la ~/" && ls -la ~/
           echo "==> ls -la ~/.acme.sh" && ls -la ~/.acme.sh
-          echo "==> ls -R | grep gao && echo Found || echo Not Found" && ls -R | grep gao && echo Found || echo Not Found
+          echo "==> ls $(pwd)/* -R | grep gao && echo Found || echo Not Found" && ls $(pwd)/* -R | grep gao && echo Found || echo Not Found
 
       - name: 4. 签发单证书-Ali
         run: |
@@ -64,7 +64,8 @@ jobs:
           echo "==> ls -la" && ls -la
           echo "==> ls -la ~/" && ls -la ~/
           echo "==> ls -la ~/.acme.sh" && ls -la ~/.acme.sh
-          echo "==> ls -R | grep gao && echo Found || echo Not Found" && ls -R | grep gao && echo Found || echo Not Found
+          echo "==> ls $(pwd)/* -R | grep gao && mv gao* certs || echo Not Found"
+          ls $(pwd)/* -R | grep gao && mv gao* certs || echo Not Found
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"
           git add certs/
